### ISSUE TITLE
[BUG]: java.lang.NoSuchMethodException: `cn.huoxian.iast.api.HttpResponse.getResponseLength`

### ISSUE THREAD

**Issue by Nizernizer** [HXSecurity/DongTai-agent-java#132]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/HXSecurity/DongTai/blob/main/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/HXSecurity/DongTai/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/HXSecurity/DongTai/issues/new/choose) without success.

### Version

1.1.0

### Installation Type

Official Docker Compose

### Service Name

DongTai-agent-java

### Describe the details of the bug and the steps to reproduce it

jdk 1.8.0_171
Tomcat 8.5.38
springboot 2.3.1.RELEASE

### Logs

```shell
java.lang.NoSuchMethodException: cn.huoxian.iast.api.HttpResponse.getResponseLength(java.lang.Integer)
        at java.lang.Class.getDeclaredMethod(Class.java:2130)
        at com.secnium.iast.core.handler.controller.impl.HttpImpl.getResponseMeta(HttpImpl.java:130)
        at com.secnium.iast.core.handler.graphy.GraphBuilder.getResponseMeta(GraphBuilder.java:35)
        at com.secnium.iast.core.handler.graphy.GraphBuilder.convertToReport(GraphBuilder.java:86)
        at com.secnium.iast.core.handler.graphy.GraphBuilder.buildAndReport(GraphBuilder.java:28)
        at com.secnium.iast.core.handler.EventListenerHandlers.leaveHttp(EventListenerHandlers.java:204)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at java.lang.iast.inject.Injecter.leaveHttp(Injecter.java:429)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:168)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.servic
```

**Comment by exexute** [comment]
Bug feedback by qunar.com security engineer.
