### ISSUE TITLE
attach模式启动

### ISSUE THREAD

**Issue by kxjhcs** [HXSecurity/DongTai-agent-java#147]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/HXSecurity/DongTai/blob/main/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/HXSecurity/DongTai/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/HXSecurity/DongTai/issues/new/choose) without success.

### Version

1.0.4

### Installation Type

Other (specify below)

### Service Name

DongTai-Core

### Describe the details of the bug and the steps to reproduce it

attach模式启动

### Additional Information

https://github.com/alibaba/arthas/commit/53a544c61f84a82a91111cad81e3d08985dbce79?diff=split
https://github.com/alibaba/arthas/issues/675

### Logs

```shell
class=org.springframework.boot.sql.init.dependency.DatabaseInitializationDependencyConfigurer$$Lambda$290/142555199\njava.lang.VerifyError\r
at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)\r
at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)\r
at com.secnium.iast.core.enhance.IastClassFileTransformer.retransform(IastClassFileTransformer.java:241)\r
at com.secnium.iast.core.enhance.IastClassFileTransformer.init(IastClassFileTransformer.java:65)\r
at com.secnium.iast.core.engines.impl.TransformEngine.start(TransformEngine.java:31)\r
at com.secnium.iast.core.AgentEngine.run(AgentEngine.java:98)\r
at com.secnium.iast.core.AgentEngine.install(AgentEngine.java:58)\r
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r
at java.lang.reflect.Method.invoke(Method.java:498)\r
at com.secnium.iast.agent.manager.EngineManager.install(EngineManager.java:177)\r
at com.secnium.iast.agent.monitor.MonitorDaemonThread.startEngine(MonitorDaemonThread.java:47)\r
at com.secnium.iast.agent.monitor.MonitorDaemonThread.run(MonitorDaemonThread.java:26)\r
at java.lang.Thread.run(Thread.java:748)\n
```

**Comment by exexute** [comment]
fixed in v1.3.1
