### ISSUE TITLE
druid环境下，字节码修改过程抛出异常

### ISSUE THREAD

**Issue by exexute** [HXSecurity/DongTai-agent-java#26]
处理`com/alibaba/druid/support/http/ResourceServlet`类时，IAST模型加载失败，导致异常，异常信息如下：

```
2021-05-28 14:31:42.547 [cn.huoxian.dongtai.engine] ERROR transform class com/alibaba/druid/support/http/ResourceServlet failed.{}
java.lang.NullPointerException: null
 at com.secnium.iast.core.handler.models.IastHookRuleModel.getRuleTypeValueByFramework(IastHookRuleModel.java:199)
 at com.secnium.iast.core.enhance.plugins.DispatchClassPlugin$ClassVisit.lazyAop(DispatchClassPlugin.java:160)
 at com.secnium.iast.core.enhance.plugins.DispatchClassPlugin$ClassVisit.visitMethod(DispatchClassPlugin.java:108)
 at com.secnium.iast.thirdparty.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1320)
 at com.secnium.iast.thirdparty.org.objectweb.asm.ClassReader.accept(ClassReader.java:711)
 at com.secnium.iast.thirdparty.org.objectweb.asm.ClassReader.accept(ClassReader.java:394)
 at com.secnium.iast.core.enhance.IastClassFileTransformer.transform(IastClassFileTransformer.java:115)
```

**Comment by exexute** [comment]
云端规则不规范导致，后期增加规则审核的功能，规则经过审核后再进行下发
