### ISSUE TITLE
[Agent compatibility]: Content-Length header already present

### ISSUE THREAD

**Issue by Bmebme** [HXSecurity/DongTai-agent-java#505]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/HXSecurity/DongTai-agent-java/blob/main/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/HXSecurity/DongTai-agent-java/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/HXSecurity/DongTai-agent-java/issues/new/choose) without success.

### Version

1.9.3

### Installation Type

Official SaaS Service

### Describe the details of the bug and the steps to reproduce it

JDK 1.

项目中某些接口在访问的时候会报出Content-Length header already present的错误

### Logs

```shell
Caused by: io.dongtai.iast.thirdparty.org.apache.http.ProtocolException: Content-Length header already present
	at io.dongtai.iast.thirdparty.org.apache.http.protocol.RequestContent.process(RequestContent.java:97)
	at io.dongtai.iast.thirdparty.org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:133)
	at io.dongtai.iast.thirdparty.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at io.dongtai.iast.thirdparty.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at io.dongtai.iast.thirdparty.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
```

**Comment by lostsnow** [comment]
Can you provide a more complete exception stacktrace
